name: "jingle_player"
description: 'A minimal, cross-platform audio player designed for short audio file playout. Designed for broadcast purposes for Technical University of Lodz Student Radio "ŻAK"'
publish_to: "none"
version: "1.0.0"
environment:
  sdk: "^3.10.4"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.8"
  audioplayers: "^6.6.0"
  file_picker: "^10.3.10"
  provider: "^6.1.5+1"
  intl: "^0.20.2"
  global_configuration: "^2.0.0"
  shared_preferences: "^2.5.4"
  path_provider: "^2.1.5"
  window_manager: "^0.5.1"
  wav: "^1.5.0"
  inno_build: "^0.4.0"
  google_fonts: ^8.0.2
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^6.0.0"
flutter:
  uses-material-design: true
  assets:
    - "assets/cfg/default_config.json"
inno_build:
  app_id: "959a879a-4174-4389-98f0-d781b27ad8c7"
