// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/pb/control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_pb_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_control_proto_rawDescGZIP(), []int{0}
}

type AudioStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveSlot           int32                  `protobuf:"varint,1,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`
	State                string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	TimeRemainingSeconds float64                `protobuf:"fixed64,3,opt,name=time_remaining_seconds,json=timeRemainingSeconds,proto3" json:"time_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AudioStatus) Reset() {
	*x = AudioStatus{}
	mi := &file_internal_pb_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStatus) ProtoMessage() {}

func (x *AudioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStatus.ProtoReflect.Descriptor instead.
func (*AudioStatus) Descriptor() ([]byte, []int) {
	return file_internal_pb_control_proto_rawDescGZIP(), []int{1}
}

func (x *AudioStatus) GetActiveSlot() int32 {
	if x != nil {
		return x.ActiveSlot
	}
	return 0
}

func (x *AudioStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AudioStatus) GetTimeRemainingSeconds() float64 {
	if x != nil {
		return x.TimeRemainingSeconds
	}
	return 0
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_internal_pb_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_control_proto_rawDescGZIP(), []int{2}
}

func (x *CommandRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *CommandRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_internal_pb_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_control_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_pb_control_proto protoreflect.FileDescriptor

const file_internal_pb_control_proto_rawDesc = "" +
	"\n" +
	"\x19internal/pb/control.proto\x12\x02pb\"\x0f\n" +
	"\rStatusRequest\"z\n" +
	"\vAudioStatus\x12\x1f\n" +
	"\vactive_slot\x18\x01 \x01(\x05R\n" +
	"activeSlot\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\x16time_remaining_seconds\x18\x03 \x01(\x01R\x14timeRemainingSeconds\"A\n" +
	"\x0eCommandRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x86\x01\n" +
	"\fAudioService\x12<\n" +
	"\x14StreamPlaybackStatus\x12\x11.pb.StatusRequest\x1a\x0f.pb.AudioStatus0\x01\x128\n" +
	"\x0eTriggerCommand\x12\x12.pb.CommandRequest\x1a\x12.pb.ActionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_internal_pb_control_proto_rawDescOnce sync.Once
	file_internal_pb_control_proto_rawDescData []byte
)

func file_internal_pb_control_proto_rawDescGZIP() []byte {
	file_internal_pb_control_proto_rawDescOnce.Do(func() {
		file_internal_pb_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_control_proto_rawDesc), len(file_internal_pb_control_proto_rawDesc)))
	})
	return file_internal_pb_control_proto_rawDescData
}

var file_internal_pb_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_control_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: pb.StatusRequest
	(*AudioStatus)(nil),    // 1: pb.AudioStatus
	(*CommandRequest)(nil), // 2: pb.CommandRequest
	(*ActionResponse)(nil), // 3: pb.ActionResponse
}
var file_internal_pb_control_proto_depIdxs = []int32{
	0, // 0: pb.AudioService.StreamPlaybackStatus:input_type -> pb.StatusRequest
	2, // 1: pb.AudioService.TriggerCommand:input_type -> pb.CommandRequest
	1, // 2: pb.AudioService.StreamPlaybackStatus:output_type -> pb.AudioStatus
	3, // 3: pb.AudioService.TriggerCommand:output_type -> pb.ActionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_control_proto_init() }
func file_internal_pb_control_proto_init() {
	if File_internal_pb_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_control_proto_rawDesc), len(file_internal_pb_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_control_proto_goTypes,
		DependencyIndexes: file_internal_pb_control_proto_depIdxs,
		MessageInfos:      file_internal_pb_control_proto_msgTypes,
	}.Build()
	File_internal_pb_control_proto = out.File
	file_internal_pb_control_proto_goTypes = nil
	file_internal_pb_control_proto_depIdxs = nil
}
