// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioService_StreamPlaybackStatus_FullMethodName      = "/pb.AudioService/StreamPlaybackStatus"
	AudioService_PlaybackCommand_FullMethodName           = "/pb.AudioService/PlaybackCommand"
	AudioService_ListPalettes_FullMethodName              = "/pb.AudioService/ListPalettes"
	AudioService_GetPalette_FullMethodName                = "/pb.AudioService/GetPalette"
	AudioService_UpdatePalette_FullMethodName             = "/pb.AudioService/UpdatePalette"
	AudioService_CreatePalette_FullMethodName             = "/pb.AudioService/CreatePalette"
	AudioService_DeletePalette_FullMethodName             = "/pb.AudioService/DeletePalette"
	AudioService_ActivatePalette_FullMethodName           = "/pb.AudioService/ActivatePalette"
	AudioService_ListAudioFiles_FullMethodName            = "/pb.AudioService/ListAudioFiles"
	AudioService_GetAudioFile_FullMethodName              = "/pb.AudioService/GetAudioFile"
	AudioService_CreateAudioFile_FullMethodName           = "/pb.AudioService/CreateAudioFile"
	AudioService_UpdateAudioFile_FullMethodName           = "/pb.AudioService/UpdateAudioFile"
	AudioService_DeleteAudioFile_FullMethodName           = "/pb.AudioService/DeleteAudioFile"
	AudioService_AssignAudioFileToSlot_FullMethodName     = "/pb.AudioService/AssignAudioFileToSlot"
	AudioService_UnassignAudioFileFromSlot_FullMethodName = "/pb.AudioService/UnassignAudioFileFromSlot"
)

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	StreamPlaybackStatus(ctx context.Context, in *AudioStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioStatus], error)
	PlaybackCommand(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error)
	ListPalettes(ctx context.Context, in *PaletteListRequest, opts ...grpc.CallOption) (*PaletteListResponse, error)
	GetPalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteGetResponse, error)
	UpdatePalette(ctx context.Context, in *Palette, opts ...grpc.CallOption) (*PaletteResponse, error)
	CreatePalette(ctx context.Context, in *Palette, opts ...grpc.CallOption) (*PaletteResponse, error)
	DeletePalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteDeleteResponse, error)
	ActivatePalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteActivateResponse, error)
	ListAudioFiles(ctx context.Context, in *ListAudioFileRequest, opts ...grpc.CallOption) (*AudioFileList, error)
	GetAudioFile(ctx context.Context, in *AudioFileID, opts ...grpc.CallOption) (*GetAudioFileResponse, error)
	CreateAudioFile(ctx context.Context, in *AudioFile, opts ...grpc.CallOption) (*AudioFileResponse, error)
	UpdateAudioFile(ctx context.Context, in *AudioFile, opts ...grpc.CallOption) (*AudioFileResponse, error)
	DeleteAudioFile(ctx context.Context, in *AudioFileID, opts ...grpc.CallOption) (*AudioFileDeleteResponse, error)
	AssignAudioFileToSlot(ctx context.Context, in *AssignAudioFileRequest, opts ...grpc.CallOption) (*PlayerSlot, error)
	UnassignAudioFileFromSlot(ctx context.Context, in *UnassignAudioFileRequest, opts ...grpc.CallOption) (*PlayerSlot, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) StreamPlaybackStatus(ctx context.Context, in *AudioStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_StreamPlaybackStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioStatusRequest, AudioStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_StreamPlaybackStatusClient = grpc.ServerStreamingClient[AudioStatus]

func (c *audioServiceClient) PlaybackCommand(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackResponse)
	err := c.cc.Invoke(ctx, AudioService_PlaybackCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) ListPalettes(ctx context.Context, in *PaletteListRequest, opts ...grpc.CallOption) (*PaletteListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteListResponse)
	err := c.cc.Invoke(ctx, AudioService_ListPalettes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) GetPalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteGetResponse)
	err := c.cc.Invoke(ctx, AudioService_GetPalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) UpdatePalette(ctx context.Context, in *Palette, opts ...grpc.CallOption) (*PaletteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteResponse)
	err := c.cc.Invoke(ctx, AudioService_UpdatePalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) CreatePalette(ctx context.Context, in *Palette, opts ...grpc.CallOption) (*PaletteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteResponse)
	err := c.cc.Invoke(ctx, AudioService_CreatePalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) DeletePalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteDeleteResponse)
	err := c.cc.Invoke(ctx, AudioService_DeletePalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) ActivatePalette(ctx context.Context, in *PaletteID, opts ...grpc.CallOption) (*PaletteActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaletteActivateResponse)
	err := c.cc.Invoke(ctx, AudioService_ActivatePalette_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) ListAudioFiles(ctx context.Context, in *ListAudioFileRequest, opts ...grpc.CallOption) (*AudioFileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioFileList)
	err := c.cc.Invoke(ctx, AudioService_ListAudioFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) GetAudioFile(ctx context.Context, in *AudioFileID, opts ...grpc.CallOption) (*GetAudioFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudioFileResponse)
	err := c.cc.Invoke(ctx, AudioService_GetAudioFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) CreateAudioFile(ctx context.Context, in *AudioFile, opts ...grpc.CallOption) (*AudioFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioFileResponse)
	err := c.cc.Invoke(ctx, AudioService_CreateAudioFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) UpdateAudioFile(ctx context.Context, in *AudioFile, opts ...grpc.CallOption) (*AudioFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioFileResponse)
	err := c.cc.Invoke(ctx, AudioService_UpdateAudioFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) DeleteAudioFile(ctx context.Context, in *AudioFileID, opts ...grpc.CallOption) (*AudioFileDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioFileDeleteResponse)
	err := c.cc.Invoke(ctx, AudioService_DeleteAudioFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) AssignAudioFileToSlot(ctx context.Context, in *AssignAudioFileRequest, opts ...grpc.CallOption) (*PlayerSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerSlot)
	err := c.cc.Invoke(ctx, AudioService_AssignAudioFileToSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioServiceClient) UnassignAudioFileFromSlot(ctx context.Context, in *UnassignAudioFileRequest, opts ...grpc.CallOption) (*PlayerSlot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerSlot)
	err := c.cc.Invoke(ctx, AudioService_UnassignAudioFileFromSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility.
type AudioServiceServer interface {
	StreamPlaybackStatus(*AudioStatusRequest, grpc.ServerStreamingServer[AudioStatus]) error
	PlaybackCommand(context.Context, *PlaybackRequest) (*PlaybackResponse, error)
	ListPalettes(context.Context, *PaletteListRequest) (*PaletteListResponse, error)
	GetPalette(context.Context, *PaletteID) (*PaletteGetResponse, error)
	UpdatePalette(context.Context, *Palette) (*PaletteResponse, error)
	CreatePalette(context.Context, *Palette) (*PaletteResponse, error)
	DeletePalette(context.Context, *PaletteID) (*PaletteDeleteResponse, error)
	ActivatePalette(context.Context, *PaletteID) (*PaletteActivateResponse, error)
	ListAudioFiles(context.Context, *ListAudioFileRequest) (*AudioFileList, error)
	GetAudioFile(context.Context, *AudioFileID) (*GetAudioFileResponse, error)
	CreateAudioFile(context.Context, *AudioFile) (*AudioFileResponse, error)
	UpdateAudioFile(context.Context, *AudioFile) (*AudioFileResponse, error)
	DeleteAudioFile(context.Context, *AudioFileID) (*AudioFileDeleteResponse, error)
	AssignAudioFileToSlot(context.Context, *AssignAudioFileRequest) (*PlayerSlot, error)
	UnassignAudioFileFromSlot(context.Context, *UnassignAudioFileRequest) (*PlayerSlot, error)
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioServiceServer struct{}

func (UnimplementedAudioServiceServer) StreamPlaybackStatus(*AudioStatusRequest, grpc.ServerStreamingServer[AudioStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamPlaybackStatus not implemented")
}
func (UnimplementedAudioServiceServer) PlaybackCommand(context.Context, *PlaybackRequest) (*PlaybackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaybackCommand not implemented")
}
func (UnimplementedAudioServiceServer) ListPalettes(context.Context, *PaletteListRequest) (*PaletteListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPalettes not implemented")
}
func (UnimplementedAudioServiceServer) GetPalette(context.Context, *PaletteID) (*PaletteGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPalette not implemented")
}
func (UnimplementedAudioServiceServer) UpdatePalette(context.Context, *Palette) (*PaletteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePalette not implemented")
}
func (UnimplementedAudioServiceServer) CreatePalette(context.Context, *Palette) (*PaletteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePalette not implemented")
}
func (UnimplementedAudioServiceServer) DeletePalette(context.Context, *PaletteID) (*PaletteDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePalette not implemented")
}
func (UnimplementedAudioServiceServer) ActivatePalette(context.Context, *PaletteID) (*PaletteActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivatePalette not implemented")
}
func (UnimplementedAudioServiceServer) ListAudioFiles(context.Context, *ListAudioFileRequest) (*AudioFileList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudioFiles not implemented")
}
func (UnimplementedAudioServiceServer) GetAudioFile(context.Context, *AudioFileID) (*GetAudioFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioFile not implemented")
}
func (UnimplementedAudioServiceServer) CreateAudioFile(context.Context, *AudioFile) (*AudioFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAudioFile not implemented")
}
func (UnimplementedAudioServiceServer) UpdateAudioFile(context.Context, *AudioFile) (*AudioFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAudioFile not implemented")
}
func (UnimplementedAudioServiceServer) DeleteAudioFile(context.Context, *AudioFileID) (*AudioFileDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAudioFile not implemented")
}
func (UnimplementedAudioServiceServer) AssignAudioFileToSlot(context.Context, *AssignAudioFileRequest) (*PlayerSlot, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignAudioFileToSlot not implemented")
}
func (UnimplementedAudioServiceServer) UnassignAudioFileFromSlot(context.Context, *UnassignAudioFileRequest) (*PlayerSlot, error) {
	return nil, status.Error(codes.Unimplemented, "method UnassignAudioFileFromSlot not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}
func (UnimplementedAudioServiceServer) testEmbeddedByValue()                      {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_StreamPlaybackStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AudioStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).StreamPlaybackStatus(m, &grpc.GenericServerStream[AudioStatusRequest, AudioStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioService_StreamPlaybackStatusServer = grpc.ServerStreamingServer[AudioStatus]

func _AudioService_PlaybackCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).PlaybackCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_PlaybackCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).PlaybackCommand(ctx, req.(*PlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_ListPalettes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaletteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).ListPalettes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_ListPalettes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).ListPalettes(ctx, req.(*PaletteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_GetPalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaletteID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).GetPalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_GetPalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).GetPalette(ctx, req.(*PaletteID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_UpdatePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Palette)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).UpdatePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_UpdatePalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).UpdatePalette(ctx, req.(*Palette))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_CreatePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Palette)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).CreatePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_CreatePalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).CreatePalette(ctx, req.(*Palette))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_DeletePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaletteID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).DeletePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_DeletePalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).DeletePalette(ctx, req.(*PaletteID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_ActivatePalette_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaletteID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).ActivatePalette(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_ActivatePalette_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).ActivatePalette(ctx, req.(*PaletteID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_ListAudioFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAudioFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).ListAudioFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_ListAudioFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).ListAudioFiles(ctx, req.(*ListAudioFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_GetAudioFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioFileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).GetAudioFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_GetAudioFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).GetAudioFile(ctx, req.(*AudioFileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_CreateAudioFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).CreateAudioFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_CreateAudioFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).CreateAudioFile(ctx, req.(*AudioFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_UpdateAudioFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).UpdateAudioFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_UpdateAudioFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).UpdateAudioFile(ctx, req.(*AudioFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_DeleteAudioFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioFileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).DeleteAudioFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_DeleteAudioFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).DeleteAudioFile(ctx, req.(*AudioFileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_AssignAudioFileToSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignAudioFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).AssignAudioFileToSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_AssignAudioFileToSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).AssignAudioFileToSlot(ctx, req.(*AssignAudioFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioService_UnassignAudioFileFromSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignAudioFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServiceServer).UnassignAudioFileFromSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioService_UnassignAudioFileFromSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServiceServer).UnassignAudioFileFromSlot(ctx, req.(*UnassignAudioFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaybackCommand",
			Handler:    _AudioService_PlaybackCommand_Handler,
		},
		{
			MethodName: "ListPalettes",
			Handler:    _AudioService_ListPalettes_Handler,
		},
		{
			MethodName: "GetPalette",
			Handler:    _AudioService_GetPalette_Handler,
		},
		{
			MethodName: "UpdatePalette",
			Handler:    _AudioService_UpdatePalette_Handler,
		},
		{
			MethodName: "CreatePalette",
			Handler:    _AudioService_CreatePalette_Handler,
		},
		{
			MethodName: "DeletePalette",
			Handler:    _AudioService_DeletePalette_Handler,
		},
		{
			MethodName: "ActivatePalette",
			Handler:    _AudioService_ActivatePalette_Handler,
		},
		{
			MethodName: "ListAudioFiles",
			Handler:    _AudioService_ListAudioFiles_Handler,
		},
		{
			MethodName: "GetAudioFile",
			Handler:    _AudioService_GetAudioFile_Handler,
		},
		{
			MethodName: "CreateAudioFile",
			Handler:    _AudioService_CreateAudioFile_Handler,
		},
		{
			MethodName: "UpdateAudioFile",
			Handler:    _AudioService_UpdateAudioFile_Handler,
		},
		{
			MethodName: "DeleteAudioFile",
			Handler:    _AudioService_DeleteAudioFile_Handler,
		},
		{
			MethodName: "AssignAudioFileToSlot",
			Handler:    _AudioService_AssignAudioFileToSlot_Handler,
		},
		{
			MethodName: "UnassignAudioFileFromSlot",
			Handler:    _AudioService_UnassignAudioFileFromSlot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPlaybackStatus",
			Handler:       _AudioService_StreamPlaybackStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}
