// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioStatusRequest) Reset() {
	*x = AudioStatusRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStatusRequest) ProtoMessage() {}

func (x *AudioStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStatusRequest.ProtoReflect.Descriptor instead.
func (*AudioStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type AudioStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActiveSlot           int32                  `protobuf:"varint,1,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`
	State                string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	TimeRemainingSeconds float64                `protobuf:"fixed64,3,opt,name=time_remaining_seconds,json=timeRemainingSeconds,proto3" json:"time_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AudioStatus) Reset() {
	*x = AudioStatus{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStatus) ProtoMessage() {}

func (x *AudioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStatus.ProtoReflect.Descriptor instead.
func (*AudioStatus) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *AudioStatus) GetActiveSlot() int32 {
	if x != nil {
		return x.ActiveSlot
	}
	return 0
}

func (x *AudioStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AudioStatus) GetTimeRemainingSeconds() float64 {
	if x != nil {
		return x.TimeRemainingSeconds
	}
	return 0
}

type PlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackRequest) Reset() {
	*x = PlaybackRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackRequest) ProtoMessage() {}

func (x *PlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackRequest.ProtoReflect.Descriptor instead.
func (*PlaybackRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *PlaybackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type PlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackResponse) Reset() {
	*x = PlaybackResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackResponse) ProtoMessage() {}

func (x *PlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackResponse.ProtoReflect.Descriptor instead.
func (*PlaybackResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *PlaybackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaybackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Palette struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slots         []*PlayerSlot          `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Palette) Reset() {
	*x = Palette{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Palette) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Palette) ProtoMessage() {}

func (x *Palette) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Palette.ProtoReflect.Descriptor instead.
func (*Palette) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *Palette) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Palette) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Palette) GetSlots() []*PlayerSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type PaletteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteResponse) Reset() {
	*x = PaletteResponse{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteResponse) ProtoMessage() {}

func (x *PaletteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteResponse.ProtoReflect.Descriptor instead.
func (*PaletteResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *PaletteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaletteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaletteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaletteResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PaletteID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteID) Reset() {
	*x = PaletteID{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteID) ProtoMessage() {}

func (x *PaletteID) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteID.ProtoReflect.Descriptor instead.
func (*PaletteID) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *PaletteID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActivatePalette struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePalette) Reset() {
	*x = ActivatePalette{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePalette) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePalette) ProtoMessage() {}

func (x *ActivatePalette) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePalette.ProtoReflect.Descriptor instead.
func (*ActivatePalette) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ActivatePalette) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaletteActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteActivateResponse) Reset() {
	*x = PaletteActivateResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteActivateResponse) ProtoMessage() {}

func (x *PaletteActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteActivateResponse.ProtoReflect.Descriptor instead.
func (*PaletteActivateResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *PaletteActivateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AudioFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFile) Reset() {
	*x = AudioFile{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFile) ProtoMessage() {}

func (x *AudioFile) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFile.ProtoReflect.Descriptor instead.
func (*AudioFile) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *AudioFile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AudioFile) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AudioFile) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type AudioFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Duration      float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileResponse) Reset() {
	*x = AudioFileResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileResponse) ProtoMessage() {}

func (x *AudioFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileResponse.ProtoReflect.Descriptor instead.
func (*AudioFileResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *AudioFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AudioFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AudioFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AudioFileResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AudioFileResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type PlayerSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	File          *AudioFile             `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSlot) Reset() {
	*x = PlayerSlot{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSlot) ProtoMessage() {}

func (x *PlayerSlot) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSlot.ProtoReflect.Descriptor instead.
func (*PlayerSlot) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerSlot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerSlot) GetFile() *AudioFile {
	if x != nil {
		return x.File
	}
	return nil
}

type PaletteListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteListRequest) Reset() {
	*x = PaletteListRequest{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteListRequest) ProtoMessage() {}

func (x *PaletteListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteListRequest.ProtoReflect.Descriptor instead.
func (*PaletteListRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

type PaletteListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Palettes      []*Palette             `protobuf:"bytes,2,rep,name=palettes,proto3" json:"palettes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteListResponse) Reset() {
	*x = PaletteListResponse{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteListResponse) ProtoMessage() {}

func (x *PaletteListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteListResponse.ProtoReflect.Descriptor instead.
func (*PaletteListResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *PaletteListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaletteListResponse) GetPalettes() []*Palette {
	if x != nil {
		return x.Palettes
	}
	return nil
}

type PaletteGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Palette       *Palette               `protobuf:"bytes,2,opt,name=palette,proto3" json:"palette,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteGetResponse) Reset() {
	*x = PaletteGetResponse{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteGetResponse) ProtoMessage() {}

func (x *PaletteGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteGetResponse.ProtoReflect.Descriptor instead.
func (*PaletteGetResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *PaletteGetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaletteGetResponse) GetPalette() *Palette {
	if x != nil {
		return x.Palette
	}
	return nil
}

type PaletteDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaletteDeleteResponse) Reset() {
	*x = PaletteDeleteResponse{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaletteDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaletteDeleteResponse) ProtoMessage() {}

func (x *PaletteDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaletteDeleteResponse.ProtoReflect.Descriptor instead.
func (*PaletteDeleteResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *PaletteDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AudioFileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioFiles    []*AudioFile           `protobuf:"bytes,1,rep,name=audio_files,json=audioFiles,proto3" json:"audio_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileList) Reset() {
	*x = AudioFileList{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileList) ProtoMessage() {}

func (x *AudioFileList) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileList.ProtoReflect.Descriptor instead.
func (*AudioFileList) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *AudioFileList) GetAudioFiles() []*AudioFile {
	if x != nil {
		return x.AudioFiles
	}
	return nil
}

type ListAudioFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAudioFileRequest) Reset() {
	*x = ListAudioFileRequest{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAudioFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAudioFileRequest) ProtoMessage() {}

func (x *ListAudioFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAudioFileRequest.ProtoReflect.Descriptor instead.
func (*ListAudioFileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

type AudioFileID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileID) Reset() {
	*x = AudioFileID{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileID) ProtoMessage() {}

func (x *AudioFileID) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileID.ProtoReflect.Descriptor instead.
func (*AudioFileID) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *AudioFileID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAudioFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AudioFile     *AudioFile             `protobuf:"bytes,2,opt,name=audio_file,json=audioFile,proto3" json:"audio_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAudioFileResponse) Reset() {
	*x = GetAudioFileResponse{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAudioFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAudioFileResponse) ProtoMessage() {}

func (x *GetAudioFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAudioFileResponse.ProtoReflect.Descriptor instead.
func (*GetAudioFileResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *GetAudioFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAudioFileResponse) GetAudioFile() *AudioFile {
	if x != nil {
		return x.AudioFile
	}
	return nil
}

type AudioFileDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFileDeleteResponse) Reset() {
	*x = AudioFileDeleteResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFileDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFileDeleteResponse) ProtoMessage() {}

func (x *AudioFileDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFileDeleteResponse.ProtoReflect.Descriptor instead.
func (*AudioFileDeleteResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *AudioFileDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AssignAudioFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	FileId        int32                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAudioFileRequest) Reset() {
	*x = AssignAudioFileRequest{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAudioFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAudioFileRequest) ProtoMessage() {}

func (x *AssignAudioFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAudioFileRequest.ProtoReflect.Descriptor instead.
func (*AssignAudioFileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *AssignAudioFileRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AssignAudioFileRequest) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type UnassignAudioFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignAudioFileRequest) Reset() {
	*x = UnassignAudioFileRequest{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignAudioFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignAudioFileRequest) ProtoMessage() {}

func (x *UnassignAudioFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignAudioFileRequest.ProtoReflect.Descriptor instead.
func (*UnassignAudioFileRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *UnassignAudioFileRequest) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x02pb\"\x14\n" +
	"\x12AudioStatusRequest\"z\n" +
	"\vAudioStatus\x12\x1f\n" +
	"\vactive_slot\x18\x01 \x01(\x05R\n" +
	"activeSlot\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\x16time_remaining_seconds\x18\x03 \x01(\x01R\x14timeRemainingSeconds\")\n" +
	"\x0fPlaybackRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\"F\n" +
	"\x10PlaybackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\aPalette\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05slots\x18\x03 \x03(\v2\x0e.pb.PlayerSlotR\x05slots\"i\n" +
	"\x0fPaletteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x1b\n" +
	"\tPaletteID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"!\n" +
	"\x0fActivatePalette\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"3\n" +
	"\x17PaletteActivateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"q\n" +
	"\tAudioFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\"\x9d\x01\n" +
	"\x11AudioFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\"?\n" +
	"\n" +
	"PlayerSlot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\x04file\x18\x02 \x01(\v2\r.pb.AudioFileR\x04file\"\x14\n" +
	"\x12PaletteListRequest\"X\n" +
	"\x13PaletteListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\bpalettes\x18\x02 \x03(\v2\v.pb.PaletteR\bpalettes\"U\n" +
	"\x12PaletteGetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\apalette\x18\x02 \x01(\v2\v.pb.PaletteR\apalette\"1\n" +
	"\x15PaletteDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\rAudioFileList\x12.\n" +
	"\vaudio_files\x18\x01 \x03(\v2\r.pb.AudioFileR\n" +
	"audioFiles\"\x16\n" +
	"\x14ListAudioFileRequest\"\x1d\n" +
	"\vAudioFileID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"^\n" +
	"\x14GetAudioFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\n" +
	"audio_file\x18\x02 \x01(\v2\r.pb.AudioFileR\taudioFile\"3\n" +
	"\x17AudioFileDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x16AssignAudioFileRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x05R\x06fileId\"3\n" +
	"\x18UnassignAudioFileRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x05R\x06slotId2\xa2\a\n" +
	"\fAudioService\x12A\n" +
	"\x14StreamPlaybackStatus\x12\x16.pb.AudioStatusRequest\x1a\x0f.pb.AudioStatus0\x01\x12<\n" +
	"\x0fPlaybackCommand\x12\x13.pb.PlaybackRequest\x1a\x14.pb.PlaybackResponse\x12?\n" +
	"\fListPalettes\x12\x16.pb.PaletteListRequest\x1a\x17.pb.PaletteListResponse\x123\n" +
	"\n" +
	"GetPalette\x12\r.pb.PaletteID\x1a\x16.pb.PaletteGetResponse\x121\n" +
	"\rUpdatePalette\x12\v.pb.Palette\x1a\x13.pb.PaletteResponse\x121\n" +
	"\rCreatePalette\x12\v.pb.Palette\x1a\x13.pb.PaletteResponse\x129\n" +
	"\rDeletePalette\x12\r.pb.PaletteID\x1a\x19.pb.PaletteDeleteResponse\x12=\n" +
	"\x0fActivatePalette\x12\r.pb.PaletteID\x1a\x1b.pb.PaletteActivateResponse\x12=\n" +
	"\x0eListAudioFiles\x12\x18.pb.ListAudioFileRequest\x1a\x11.pb.AudioFileList\x129\n" +
	"\fGetAudioFile\x12\x0f.pb.AudioFileID\x1a\x18.pb.GetAudioFileResponse\x127\n" +
	"\x0fCreateAudioFile\x12\r.pb.AudioFile\x1a\x15.pb.AudioFileResponse\x127\n" +
	"\x0fUpdateAudioFile\x12\r.pb.AudioFile\x1a\x15.pb.AudioFileResponse\x12?\n" +
	"\x0fDeleteAudioFile\x12\x0f.pb.AudioFileID\x1a\x1b.pb.AudioFileDeleteResponse\x12C\n" +
	"\x15AssignAudioFileToSlot\x12\x1a.pb.AssignAudioFileRequest\x1a\x0e.pb.PlayerSlot\x12I\n" +
	"\x19UnassignAudioFileFromSlot\x12\x1c.pb.UnassignAudioFileRequest\x1a\x0e.pb.PlayerSlotB\x06Z\x04./pbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_control_proto_goTypes = []any{
	(*AudioStatusRequest)(nil),       // 0: pb.AudioStatusRequest
	(*AudioStatus)(nil),              // 1: pb.AudioStatus
	(*PlaybackRequest)(nil),          // 2: pb.PlaybackRequest
	(*PlaybackResponse)(nil),         // 3: pb.PlaybackResponse
	(*Palette)(nil),                  // 4: pb.Palette
	(*PaletteResponse)(nil),          // 5: pb.PaletteResponse
	(*PaletteID)(nil),                // 6: pb.PaletteID
	(*ActivatePalette)(nil),          // 7: pb.ActivatePalette
	(*PaletteActivateResponse)(nil),  // 8: pb.PaletteActivateResponse
	(*AudioFile)(nil),                // 9: pb.AudioFile
	(*AudioFileResponse)(nil),        // 10: pb.AudioFileResponse
	(*PlayerSlot)(nil),               // 11: pb.PlayerSlot
	(*PaletteListRequest)(nil),       // 12: pb.PaletteListRequest
	(*PaletteListResponse)(nil),      // 13: pb.PaletteListResponse
	(*PaletteGetResponse)(nil),       // 14: pb.PaletteGetResponse
	(*PaletteDeleteResponse)(nil),    // 15: pb.PaletteDeleteResponse
	(*AudioFileList)(nil),            // 16: pb.AudioFileList
	(*ListAudioFileRequest)(nil),     // 17: pb.ListAudioFileRequest
	(*AudioFileID)(nil),              // 18: pb.AudioFileID
	(*GetAudioFileResponse)(nil),     // 19: pb.GetAudioFileResponse
	(*AudioFileDeleteResponse)(nil),  // 20: pb.AudioFileDeleteResponse
	(*AssignAudioFileRequest)(nil),   // 21: pb.AssignAudioFileRequest
	(*UnassignAudioFileRequest)(nil), // 22: pb.UnassignAudioFileRequest
}
var file_control_proto_depIdxs = []int32{
	11, // 0: pb.Palette.slots:type_name -> pb.PlayerSlot
	9,  // 1: pb.PlayerSlot.file:type_name -> pb.AudioFile
	4,  // 2: pb.PaletteListResponse.palettes:type_name -> pb.Palette
	4,  // 3: pb.PaletteGetResponse.palette:type_name -> pb.Palette
	9,  // 4: pb.AudioFileList.audio_files:type_name -> pb.AudioFile
	9,  // 5: pb.GetAudioFileResponse.audio_file:type_name -> pb.AudioFile
	0,  // 6: pb.AudioService.StreamPlaybackStatus:input_type -> pb.AudioStatusRequest
	2,  // 7: pb.AudioService.PlaybackCommand:input_type -> pb.PlaybackRequest
	12, // 8: pb.AudioService.ListPalettes:input_type -> pb.PaletteListRequest
	6,  // 9: pb.AudioService.GetPalette:input_type -> pb.PaletteID
	4,  // 10: pb.AudioService.UpdatePalette:input_type -> pb.Palette
	4,  // 11: pb.AudioService.CreatePalette:input_type -> pb.Palette
	6,  // 12: pb.AudioService.DeletePalette:input_type -> pb.PaletteID
	6,  // 13: pb.AudioService.ActivatePalette:input_type -> pb.PaletteID
	17, // 14: pb.AudioService.ListAudioFiles:input_type -> pb.ListAudioFileRequest
	18, // 15: pb.AudioService.GetAudioFile:input_type -> pb.AudioFileID
	9,  // 16: pb.AudioService.CreateAudioFile:input_type -> pb.AudioFile
	9,  // 17: pb.AudioService.UpdateAudioFile:input_type -> pb.AudioFile
	18, // 18: pb.AudioService.DeleteAudioFile:input_type -> pb.AudioFileID
	21, // 19: pb.AudioService.AssignAudioFileToSlot:input_type -> pb.AssignAudioFileRequest
	22, // 20: pb.AudioService.UnassignAudioFileFromSlot:input_type -> pb.UnassignAudioFileRequest
	1,  // 21: pb.AudioService.StreamPlaybackStatus:output_type -> pb.AudioStatus
	3,  // 22: pb.AudioService.PlaybackCommand:output_type -> pb.PlaybackResponse
	13, // 23: pb.AudioService.ListPalettes:output_type -> pb.PaletteListResponse
	14, // 24: pb.AudioService.GetPalette:output_type -> pb.PaletteGetResponse
	5,  // 25: pb.AudioService.UpdatePalette:output_type -> pb.PaletteResponse
	5,  // 26: pb.AudioService.CreatePalette:output_type -> pb.PaletteResponse
	15, // 27: pb.AudioService.DeletePalette:output_type -> pb.PaletteDeleteResponse
	8,  // 28: pb.AudioService.ActivatePalette:output_type -> pb.PaletteActivateResponse
	16, // 29: pb.AudioService.ListAudioFiles:output_type -> pb.AudioFileList
	19, // 30: pb.AudioService.GetAudioFile:output_type -> pb.GetAudioFileResponse
	10, // 31: pb.AudioService.CreateAudioFile:output_type -> pb.AudioFileResponse
	10, // 32: pb.AudioService.UpdateAudioFile:output_type -> pb.AudioFileResponse
	20, // 33: pb.AudioService.DeleteAudioFile:output_type -> pb.AudioFileDeleteResponse
	11, // 34: pb.AudioService.AssignAudioFileToSlot:output_type -> pb.PlayerSlot
	11, // 35: pb.AudioService.UnassignAudioFileFromSlot:output_type -> pb.PlayerSlot
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
