// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AudioFile struct {
	ID       int64
	Name     string
	Size     int64
	Duration float64
}

type Palette struct {
	ID         int64
	Name       string
	Slot0File  sql.NullInt64
	Slot1File  sql.NullInt64
	Slot2File  sql.NullInt64
	Slot3File  sql.NullInt64
	Slot4File  sql.NullInt64
	Slot5File  sql.NullInt64
	Slot6File  sql.NullInt64
	Slot7File  sql.NullInt64
	Slot8File  sql.NullInt64
	Slot9File  sql.NullInt64
	Slot10File sql.NullInt64
	Slot11File sql.NullInt64
	Slot12File sql.NullInt64
	Slot13File sql.NullInt64
	Slot14File sql.NullInt64
	Slot15File sql.NullInt64
}
