// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type AudioFile struct {
	ID       int64
	Name     string
	Path     string
	Duration float64
}

type Palette struct {
	ID         int64
	Name       string
	Slot0File  interface{}
	Slot1File  interface{}
	Slot2File  interface{}
	Slot3File  interface{}
	Slot4File  interface{}
	Slot5File  interface{}
	Slot6File  interface{}
	Slot7File  interface{}
	Slot8File  interface{}
	Slot9File  interface{}
	Slot10File interface{}
	Slot11File interface{}
	Slot12File interface{}
	Slot13File interface{}
	Slot14File interface{}
	Slot15File interface{}
}
