// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createAudioFile = `-- name: CreateAudioFile :one
INSERT INTO audio_files (
  name, path, duration
) VALUES (
  ?, ?, ?
)
RETURNING id, name, path, duration
`

type CreateAudioFileParams struct {
	Name     string
	Path     string
	Duration float64
}

func (q *Queries) CreateAudioFile(ctx context.Context, arg CreateAudioFileParams) (AudioFile, error) {
	row := q.db.QueryRowContext(ctx, createAudioFile, arg.Name, arg.Path, arg.Duration)
	var i AudioFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Duration,
	)
	return i, err
}

const createPalette = `-- name: CreatePalette :one
INSERT INTO palettes (
  name, slot_0_file, slot_1_file, slot_2_file, slot_3_file, slot_4_file, slot_5_file, slot_6_file, slot_7_file, slot_8_file, slot_9_file, slot_10_file,
  slot_11_file, slot_12_file, slot_13_file, slot_14_file, slot_15_file
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, slot_0_file, slot_1_file, slot_2_file, slot_3_file, slot_4_file, slot_5_file, slot_6_file, slot_7_file, slot_8_file, slot_9_file, slot_10_file, slot_11_file, slot_12_file, slot_13_file, slot_14_file, slot_15_file
`

type CreatePaletteParams struct {
	Name       string
	Slot0File  sql.NullInt64
	Slot1File  sql.NullInt64
	Slot2File  sql.NullInt64
	Slot3File  sql.NullInt64
	Slot4File  sql.NullInt64
	Slot5File  sql.NullInt64
	Slot6File  sql.NullInt64
	Slot7File  sql.NullInt64
	Slot8File  sql.NullInt64
	Slot9File  sql.NullInt64
	Slot10File sql.NullInt64
	Slot11File sql.NullInt64
	Slot12File sql.NullInt64
	Slot13File sql.NullInt64
	Slot14File sql.NullInt64
	Slot15File sql.NullInt64
}

func (q *Queries) CreatePalette(ctx context.Context, arg CreatePaletteParams) (Palette, error) {
	row := q.db.QueryRowContext(ctx, createPalette,
		arg.Name,
		arg.Slot0File,
		arg.Slot1File,
		arg.Slot2File,
		arg.Slot3File,
		arg.Slot4File,
		arg.Slot5File,
		arg.Slot6File,
		arg.Slot7File,
		arg.Slot8File,
		arg.Slot9File,
		arg.Slot10File,
		arg.Slot11File,
		arg.Slot12File,
		arg.Slot13File,
		arg.Slot14File,
		arg.Slot15File,
	)
	var i Palette
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slot0File,
		&i.Slot1File,
		&i.Slot2File,
		&i.Slot3File,
		&i.Slot4File,
		&i.Slot5File,
		&i.Slot6File,
		&i.Slot7File,
		&i.Slot8File,
		&i.Slot9File,
		&i.Slot10File,
		&i.Slot11File,
		&i.Slot12File,
		&i.Slot13File,
		&i.Slot14File,
		&i.Slot15File,
	)
	return i, err
}

const deleteAudioFile = `-- name: DeleteAudioFile :exec
DELETE FROM audio_files
WHERE id = ?
`

func (q *Queries) DeleteAudioFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAudioFile, id)
	return err
}

const deletePalette = `-- name: DeletePalette :exec
DELETE FROM palettes
WHERE id = ?
`

func (q *Queries) DeletePalette(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePalette, id)
	return err
}

const getAudioFile = `-- name: GetAudioFile :one
SELECT id, name, path, duration FROM audio_files
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAudioFile(ctx context.Context, id int64) (AudioFile, error) {
	row := q.db.QueryRowContext(ctx, getAudioFile, id)
	var i AudioFile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Duration,
	)
	return i, err
}

const getPalette = `-- name: GetPalette :one
SELECT id, name, slot_0_file, slot_1_file, slot_2_file, slot_3_file, slot_4_file, slot_5_file, slot_6_file, slot_7_file, slot_8_file, slot_9_file, slot_10_file, slot_11_file, slot_12_file, slot_13_file, slot_14_file, slot_15_file FROM palettes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPalette(ctx context.Context, id int64) (Palette, error) {
	row := q.db.QueryRowContext(ctx, getPalette, id)
	var i Palette
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slot0File,
		&i.Slot1File,
		&i.Slot2File,
		&i.Slot3File,
		&i.Slot4File,
		&i.Slot5File,
		&i.Slot6File,
		&i.Slot7File,
		&i.Slot8File,
		&i.Slot9File,
		&i.Slot10File,
		&i.Slot11File,
		&i.Slot12File,
		&i.Slot13File,
		&i.Slot14File,
		&i.Slot15File,
	)
	return i, err
}

const listAudioFiles = `-- name: ListAudioFiles :many
SELECT id, name, path, duration FROM audio_files
ORDER BY name
`

func (q *Queries) ListAudioFiles(ctx context.Context) ([]AudioFile, error) {
	rows, err := q.db.QueryContext(ctx, listAudioFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudioFile
	for rows.Next() {
		var i AudioFile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPalettes = `-- name: ListPalettes :many
SELECT id, name, slot_0_file, slot_1_file, slot_2_file, slot_3_file, slot_4_file, slot_5_file, slot_6_file, slot_7_file, slot_8_file, slot_9_file, slot_10_file, slot_11_file, slot_12_file, slot_13_file, slot_14_file, slot_15_file FROM palettes
ORDER BY name
`

func (q *Queries) ListPalettes(ctx context.Context) ([]Palette, error) {
	rows, err := q.db.QueryContext(ctx, listPalettes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Palette
	for rows.Next() {
		var i Palette
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slot0File,
			&i.Slot1File,
			&i.Slot2File,
			&i.Slot3File,
			&i.Slot4File,
			&i.Slot5File,
			&i.Slot6File,
			&i.Slot7File,
			&i.Slot8File,
			&i.Slot9File,
			&i.Slot10File,
			&i.Slot11File,
			&i.Slot12File,
			&i.Slot13File,
			&i.Slot14File,
			&i.Slot15File,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAudioFile = `-- name: UpdateAudioFile :exec
UPDATE audio_files
set name = ?,
path = ?,
duration = ?
WHERE id = ?
`

type UpdateAudioFileParams struct {
	Name     string
	Path     string
	Duration float64
	ID       int64
}

func (q *Queries) UpdateAudioFile(ctx context.Context, arg UpdateAudioFileParams) error {
	_, err := q.db.ExecContext(ctx, updateAudioFile,
		arg.Name,
		arg.Path,
		arg.Duration,
		arg.ID,
	)
	return err
}

const updatePalette = `-- name: UpdatePalette :exec
UPDATE palettes
set name = ?,
slot_0_file = ?,
slot_1_file = ?,
slot_2_file = ?,
slot_3_file = ?,
slot_4_file = ?,
slot_5_file = ?,
slot_6_file = ?,
slot_7_file = ?,
slot_8_file = ?,
slot_9_file = ?,
slot_10_file = ?,
slot_11_file = ?,
slot_12_file = ?,
slot_13_file = ?,
slot_14_file = ?,
slot_15_file = ?
WHERE id = ?
`

type UpdatePaletteParams struct {
	Name       string
	Slot0File  sql.NullInt64
	Slot1File  sql.NullInt64
	Slot2File  sql.NullInt64
	Slot3File  sql.NullInt64
	Slot4File  sql.NullInt64
	Slot5File  sql.NullInt64
	Slot6File  sql.NullInt64
	Slot7File  sql.NullInt64
	Slot8File  sql.NullInt64
	Slot9File  sql.NullInt64
	Slot10File sql.NullInt64
	Slot11File sql.NullInt64
	Slot12File sql.NullInt64
	Slot13File sql.NullInt64
	Slot14File sql.NullInt64
	Slot15File sql.NullInt64
	ID         int64
}

func (q *Queries) UpdatePalette(ctx context.Context, arg UpdatePaletteParams) error {
	_, err := q.db.ExecContext(ctx, updatePalette,
		arg.Name,
		arg.Slot0File,
		arg.Slot1File,
		arg.Slot2File,
		arg.Slot3File,
		arg.Slot4File,
		arg.Slot5File,
		arg.Slot6File,
		arg.Slot7File,
		arg.Slot8File,
		arg.Slot9File,
		arg.Slot10File,
		arg.Slot11File,
		arg.Slot12File,
		arg.Slot13File,
		arg.Slot14File,
		arg.Slot15File,
		arg.ID,
	)
	return err
}
