name: Build Windows App Installer - alpha
on:
  push:
    tags:
      - "**-alpha*"

permissions:
  contents: write

jobs:
  windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Flutter
        uses: subosito/flutter-action@v2

      - name: Generate version code
        id: version-code
        run: |
          echo -n "code=$(git rev-list --count ${{ github.ref }})" >> $GITHUB_OUTPUT

      - name: Build Windows App
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --build-name ${{ github.ref_name }} --build-number ${{ steps.version-code.outputs.code }}

      - name: Build iss script
        run: dart run inno_bundle:build --no-app --release --no-installer --app-version ${{ github.ref_name }}

      - name: Output config into github output
        id: envs
        # thanks to https://github.com/actions/runner/issues/2224#issuecomment-1289925992
        run: echo $(dart run inno_bundle:build --envs --no-hf) | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: ./build/windows/x64/installer/Release/inno-script.iss

      - name: Release installer
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./build/windows/x64/installer/Release/${{ steps.envs.outputs.APP_NAME_CAMEL_CASE }}-x86_64-${{ steps.envs.outputs.APP_VERSION }}-Installer.exe
          name: "${{ steps.envs.outputs.APP_VERSION }}"
          target_commitish: "${{ github.sha }}"
          tag_name: "${{ github.ref_name }}"
          prerelease: true
          generate_release_notes: true
